- [ ] synchronize habits format to take it from 1 place, for manual input mostly
- [ ] create a table generator based on extracted habits
- [ ] ask for user if the user is correct and if no let him to add changes